#!/usr/bin/env node
/**
 * codegen-tsgen.mjs — M4.3
 *
 * Reads .codegen/book-tools.schema.json (output of codegen-emit.mjs),
 * wraps each model in a minimal OpenAPI 3.1 document, runs openapi-typescript
 * to produce TypeScript, and writes src/types/generated/book-tools.ts.
 *
 * The auto-generated header marks the file as machine-generated. Consumers
 * import types from '@pdomain/pdomain-ui/types'.
 *
 * Flags:
 *   --book-tools-only   Only generate book-tools types (skip pdomain-ocr-ops)
 *
 * Environment overrides (used in tests):
 *   CODEGEN_SCHEMA_IN    Path to input JSON Schema file
 *   CODEGEN_TYPES_OUT    Path for output TypeScript file
 */

import { readFileSync, writeFileSync, mkdirSync } from 'fs'
import { execFileSync } from 'child_process'
import { resolve, dirname, join } from 'path'
import { fileURLToPath } from 'url'
import { mkdtempSync, rmSync } from 'fs'
import { tmpdir } from 'os'

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(__dirname, '..')

const GENERATED_HEADER = `// AUTO-GENERATED by scripts/codegen-tsgen.mjs from pdomain-book-tools schemas.
// DO NOT EDIT. Re-generate by running: pnpm codegen
// See: codegen.versions.json for pinned source versions.
`

function parseArgs(argv) {
  const args = argv.slice(2)
  return {
    bookToolsOnly: args.includes('--book-tools-only'),
  }
}

/**
 * Rewrite all $ref values in `obj` from `#/$defs/Name` to
 * `#/components/schemas/Name` so that openapi-typescript can resolve them.
 * Also rewrites discriminator.mapping values which Pydantic emits as
 * `#/$defs/Name` strings (not $ref objects) but which Redocly resolves
 * the same way.
 */
function rewriteRefs(obj) {
  if (typeof obj !== 'object' || obj === null) return obj
  if (Array.isArray(obj)) return obj.map(rewriteRefs)

  const result = {}
  for (const [key, value] of Object.entries(obj)) {
    if (key === '$ref' && typeof value === 'string') {
      // #/$defs/Foo → #/components/schemas/Foo
      result[key] = value.replace(/^#\/\$defs\//, '#/components/schemas/')
    } else if (key === 'mapping' && typeof value === 'object' && value !== null && !Array.isArray(value)) {
      // discriminator.mapping values: { "key": "#/$defs/Foo" } → { "key": "#/components/schemas/Foo" }
      const rewrittenMapping = {}
      for (const [mapKey, mapVal] of Object.entries(value)) {
        rewrittenMapping[mapKey] =
          typeof mapVal === 'string'
            ? mapVal.replace(/^#\/\$defs\//, '#/components/schemas/')
            : mapVal
      }
      result[key] = rewrittenMapping
    } else {
      result[key] = rewriteRefs(value)
    }
  }
  return result
}

/**
 * Wrap a flat {ModelName: jsonSchema} map into an OpenAPI 3.1.0 document
 * with all schemas under components.schemas. Handles $defs merging so that
 * intra-model references resolve correctly.
 */
function wrapInOpenAPI(schemas, title = 'pdomain-book-tools generated schemas') {
  // Collect all $defs from all top-level schemas and merge them
  const mergedDefs = {}
  const cleanSchemas = {}

  for (const [name, schema] of Object.entries(schemas)) {
    const { $defs, ...rest } = schema
    if ($defs) {
      Object.assign(mergedDefs, $defs)
    }
    cleanSchemas[name] = rest
  }

  // Build the components.schemas map, including both top-level models
  // and any $defs (sub-types referenced via $ref)
  const allComponents = { ...cleanSchemas, ...mergedDefs }

  // Rewrite $ref paths before building the OpenAPI document
  const rewrittenComponents = rewriteRefs(allComponents)

  return {
    openapi: '3.1.0',
    info: {
      title,
      version: '0.0.0',
    },
    components: {
      schemas: rewrittenComponents,
    },
  }
}

async function main() {
  const opts = parseArgs(process.argv)

  const schemaIn =
    process.env['CODEGEN_SCHEMA_IN'] ??
    join(REPO_ROOT, '.codegen', 'book-tools.schema.json')

  const typesOut =
    process.env['CODEGEN_TYPES_OUT'] ??
    join(REPO_ROOT, 'src', 'types', 'generated', 'book-tools.ts')

  console.log(`Reading schema: ${schemaIn}`)
  console.log(`Writing types: ${typesOut}`)

  const rawSchema = JSON.parse(readFileSync(schemaIn, 'utf-8'))
  const openApiDoc = wrapInOpenAPI(rawSchema)

  // Write the wrapped OpenAPI doc to a tmp file for openapi-typescript CLI
  const tmpDir = mkdtempSync(join(tmpdir(), 'codegen-tsgen-'))
  const tmpSchemaPath = join(tmpDir, 'openapi.json')

  // openapi-typescript CLI path — reused for both book-tools and ocr-ops
  const cliPath = join(REPO_ROOT, 'node_modules/openapi-typescript/bin/cli.js')
  // Prettier bin — used to format generated files so codegen-check stays stable
  const prettierBin = join(REPO_ROOT, 'node_modules/.bin/prettier')

  try {
    writeFileSync(tmpSchemaPath, JSON.stringify(openApiDoc, null, 2), 'utf-8')

    // Ensure output directory exists
    mkdirSync(join(typesOut, '..'), { recursive: true })

    // Run openapi-typescript CLI
    const result = execFileSync(
      'node',
      [
        cliPath,
        tmpSchemaPath,
        '--export-type',
        '--root-types',
        '--root-types-no-schema-prefix',
      ],
      {
        encoding: 'utf-8',
        cwd: REPO_ROOT,
      },
    )

    // Prepend our custom header (replacing openapi-typescript's header)
    const withHeader = GENERATED_HEADER + '\n' + result

    // Format through Prettier so codegen-check stays stable when format-check
    // is also in CI. Without this, openapi-typescript output differs from
    // Prettier's canonical form and git diff --exit-code always fails.
    const formatted = execFileSync(
      prettierBin,
      ['--stdin-filepath', typesOut, '--parser', 'typescript'],
      { input: withHeader, encoding: 'utf-8', cwd: REPO_ROOT },
    )

    writeFileSync(typesOut, formatted, 'utf-8')
    console.log(`codegen:tsgen complete — wrote ${typesOut}`)
  } finally {
    rmSync(tmpDir, { recursive: true, force: true })
  }

  if (!opts.bookToolsOnly) {
    const opsSchemaIn =
      process.env['CODEGEN_OPS_SCHEMA_IN'] ??
      join(REPO_ROOT, '.codegen', 'ocr-ops.schema.json')

    const opsTypesOut =
      process.env['CODEGEN_OPS_TYPES_OUT'] ??
      join(REPO_ROOT, 'src', 'types', 'generated', 'ocr-ops.ts')

    const OPS_GENERATED_HEADER = `// AUTO-GENERATED by scripts/codegen-tsgen.mjs from pdomain-ocr-ops schemas.\n// DO NOT EDIT. Re-generate by running: pnpm codegen\n// See: codegen.versions.json for pinned source versions.\n`

    console.log(`Reading ops schema: ${opsSchemaIn}`)
    console.log(`Writing ops types: ${opsTypesOut}`)

    const opsRawSchema = JSON.parse(readFileSync(opsSchemaIn, 'utf-8'))
    const opsOpenApiDoc = wrapInOpenAPI(opsRawSchema, 'pdomain-ocr-ops generated schemas')

    const opsTmpDir = mkdtempSync(join(tmpdir(), 'codegen-tsgen-ops-'))
    const opsTmpSchemaPath = join(opsTmpDir, 'openapi.json')

    try {
      writeFileSync(opsTmpSchemaPath, JSON.stringify(opsOpenApiDoc, null, 2), 'utf-8')
      mkdirSync(join(opsTypesOut, '..'), { recursive: true })

      const opsResult = execFileSync(
        'node',
        [cliPath, opsTmpSchemaPath, '--export-type', '--root-types', '--root-types-no-schema-prefix'],
        { encoding: 'utf-8', cwd: REPO_ROOT },
      )

      const opsWithHeader = OPS_GENERATED_HEADER + '\n' + opsResult
      const opsFormatted = execFileSync(
        prettierBin,
        ['--stdin-filepath', opsTypesOut, '--parser', 'typescript'],
        { input: opsWithHeader, encoding: 'utf-8', cwd: REPO_ROOT },
      )
      writeFileSync(opsTypesOut, opsFormatted, 'utf-8')
      console.log(`codegen:tsgen (ocr-ops) complete — wrote ${opsTypesOut}`)
    } finally {
      rmSync(opsTmpDir, { recursive: true, force: true })
    }
  }
}

main().catch((err) => {
  console.error('codegen:tsgen failed:', err.message)
  process.exit(1)
})
